version: "3.9"
# O serviço que está sendo executado no Docker.
services:
  web:
    # Imagem que estamos usando.
    image: nginx:latest
    volumes:
      # Diretório do volume, compartilhando somente o arquivo em modo de leitura.
      - "/home/docker-swarm-exemplo/docker-swarm/docker-swarm/docker.html:/usr/share/nginx/html/docker.html:ro"
    networks:
      # Permitindo acesso universal ao container.
      - global
    deploy:
      # Configurações do swarm para limitar os containers.
      replicas: 3
      # Recursos de cada container.
      resources:
        # Quantidade máxima de recursos que o container pode usar.
        limits:
          cpus: "1"
          memory: 1G
          # Quantidade máxima de processos da aplicação, configuração de risco.
          # pids: 100
        # Quantidade reservada mínima para este container.
        reservations:
          cpus: "0.1"
          memory: 20M
      # Configuração de reinicialização: reinicie em caso de falha.
      restart_policy:
        condition: on-failure
    # Porta para expor o serviço.
    ports:
      - "80:80"
networks:
  # Apelido do networks.
  global:
    # driver overlay é próprio do Docker Swarm.
    driver: overlay
